name: Delete Issue on Label

on:
  issues:
    types:
      - labeled

permissions:
  contents:
    write

jobs:
  delete_issue:
    if: contains( github.event.issue.labels.*.name, 'delete')

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Delete Post
      run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} python scripts/delete_post.py ${{ github.event.issue.number }}

    - name: commit and push
      continue-on-error: true
      run: |
        git config --global user.name 'Post Editor'
        git config --global user.email 'TheodoreKrypton@users.noreply.github.com'
        git add .
        git commit -m "delete post"
        git push
        
    - name: Delete issue
      uses: vtcaregorodtcev/delete-issue@main
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        issue_node_id: ${{ github.event.issue.node_id }}
