name: Delete Issue on Label

on:
  issues:
    types:
      - labeled

permissions:
  issues:
    write

jobs:
  delete_issue:
    if: contains( github.event.issue.labels.*.name, 'delete')

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete issue on "delete" label
      uses: vtcaregorodtcev/delete-issue@main
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        issue_node_id: ${{ github.event.issue.node_id }}
