name: Generate GeoJSON

on:
  workflow_dispatch:

permissions:
  contents:
    write

jobs:
  generate-geojson:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: geojson
          path: dist/geojson
