name: Generate GeoJSON

on:
  workflow_dispatch:

permissions:
  contents:
    write

jobs:
  generate-geojson:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    
    - name: generate geojson
      run: |
        python scripts/generate_map.py
    
    - name: Check out to map branch
      uses: actions/checkout@v2
      with:
        ref: map

    - name: commit and push
      run: |
          git config --global user.name 'Post Editor'
          git config --global user.email 'TheodoreKrypton@users.noreply.github.com'
          git add .
          git commit -m "generate map"
          git push
